#!/usr/bin/env bash
if ! command -v nginx &> /dev/null
	then
		echo "Nginx is not installed. Installing..."
		apt-get update
		apt-get install nginx -y
fi

sed -i 's/user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 8080;/' /etc/nginx/sites-available/default
service nginx restart
echo "Nginx configured to run as nginx user and listen on port 8080."
